In [6]:
# documentation: https://opensource.com/article/21/9/python-numpy
import numpy as np
import time as time

my_list = range(1, 1000000000)
len(my_list)

999999999

In [7]:
start = time.time()
min(my_list)

print('Time elapsed in milliseconds: ' + str((time.time() - start) * 1000))

Time elapsed in milliseconds: 71367.77400970459


In [8]:
my_list = np.arange(1, 1000000000)
start = time.time()
my_list.min()

print('Time elapsed in milliseconds: ' + str((time.time() - start) * 1000))

Time elapsed in milliseconds: 2463.4110927581787


In [9]:
my_ndarray = np.array([1, 2, 3, 4, 5])
print(my_ndarray)
type(my_ndarray)

[1 2 3 4 5]


numpy.ndarray

In [11]:
np.shape(my_ndarray)

my_ndarray2 = np.array([(1, 2, 3), (4, 5, 6)])
np.shape(my_ndarray2)

(2, 3)

In [16]:
my_ndarray.dtype
my_ndarray.size

5

In [13]:
my_ndarray2 = np.array([1, 2.0, 3])
print(my_ndarray2)
my_ndarray2.dtype

[1. 2. 3.]


dtype('float64')

In [14]:
my_ndarray2 = np.array([1, '2', 3])
print(my_ndarray2)
my_ndarray2.dtype

['1' '2' '3']


dtype('<U11')

In [17]:
my_ndarray = np.zeros([2,3], dtype=int)
print(my_ndarray)

[[0 0 0]
 [0 0 0]]


In [18]:
my_ndarray = np.full([2,3], 10, dtype=int)
print(my_ndarray)

[[10 10 10]
 [10 10 10]]


In [19]:
my_ndarray = np.eye(3, dtype=int)
print(my_ndarray)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [21]:
my_ndarray = np.arange(1, 20, 3)
print(my_ndarray)
print(my_ndarray[2:4])

[ 1  4  7 10 13 16 19]
[ 7 10]


In [22]:
my_ndarray[-1:] = 100
print(my_ndarray)

[  1   4   7  10  13  16 100]


In [24]:
my_ndarray = np.array([1, 2, 3, 4, 5])
my_ndarray2 = np.array([6, 7, 8, 9, 10])

print(my_ndarray2 + my_ndarray)
print(my_ndarray2 - my_ndarray)
print(my_ndarray2 * my_ndarray)


[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]


In [25]:
my_ndarray = np.array([3, 1, 2, 5, 4])
my_ndarray.sort()
print(my_ndarray)

[1 2 3 4 5]


In [26]:
my_ndarray = np.array([3, 1, 2, 5, 4])
print(np.sort(my_ndarray))
print(my_ndarray)

[1 2 3 4 5]
[3 1 2 5 4]
